# Generated by Django 5.1.2 on 2024-12-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armory', '0002_armor_description_weapon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='description',
            field=models.TextField(default='Add description'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.TextField(default='Add description'),
        ),
    ]
