# Generated by Django 5.1.2 on 2024-12-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(default='default_image.jpg', max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('element', models.CharField(max_length=200)),
                ('casting_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Seconds to Cast')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20000)),
                ('image_url', models.CharField(default='default_image.jpg', max_length=200)),
                ('last_edited', models.DateTimeField(verbose_name='Time Page Was Last Edited')),
            ],
        ),
    ]
