# Generated by Django 5.1.2 on 2024-12-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image_url',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(default='static/default_image.jpg', upload_to='img'),
        ),
    ]
