# Generated by Django 5.1.2 on 2024-12-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_remove_skill_image_url_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(default='default_image.jpg', upload_to='img'),
        ),
    ]
