# Generated by Django 5.1.2 on 2024-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_alter_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='wikipage',
            name='last_edited',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='title',
            field=models.CharField(default='Test', max_length=500),
            preserve_default=False,
        ),
    ]
