# Generated by Django 5.1.2 on 2024-12-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_remove_wikipage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='wiki_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.wikipage'),
            preserve_default=False,
        ),
    ]
